# Generated by Django 5.0.6 on 2024-06-19 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at']},
        ),
        migrations.RemoveField(
            model_name='news',
            name='published_time',
        ),
        migrations.AddField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
